runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /model
  static_dir: model

- url: /static
  static_dir: static

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "1.5"

